/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Buchungen.java
 *
 * Created on 29.09.2011, 22:04:32
 */
package at.jollydays.booking.ui;

/**
 *
 * @author Gunter Reinitzer
 */
public class Buchungen extends javax.swing.JPanel {

    /** Creates new form Buchungen */
    public Buchungen() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
