/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelSettings.java
 *
 * Created on 05.12.2010, 14:13:35
 */
package at.jollydays.booking.ui;

import at.jollydays.booking.Globals;
import at.jollydays.booking.Processing;
import at.jollydays.booking.control.ConfigurationController;
import java.awt.Cursor;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;

/**
 *
 * @author Gunter Reinitzer
 */
public class JPanelSettings extends javax.swing.JPanel {

    ConfigurationController configurationController;

    /** Creates new form JPanelSettings */
    public JPanelSettings() {
        initComponents();

        if (java.beans.Beans.isDesignTime()) return;
        setValues();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextARLastNumber = new javax.swing.JTextField();
        jLabelARNextNumber = new javax.swing.JLabel();
        jTextARPacketSize = new javax.swing.JTextField();
        jLabelARPacketSize = new javax.swing.JLabel();
        jLabelAR = new javax.swing.JLabel();
        jLabelER = new javax.swing.JLabel();
        jTextERLastNumber = new javax.swing.JTextField();
        jLabelERNextNumber = new javax.swing.JLabel();
        jTextERPacketSize = new javax.swing.JTextField();
        jLabelERPacketSize = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonFileChooser = new javax.swing.JButton();
        jTextFileChooser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonRun = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextLogChooser = new javax.swing.JTextField();
        jButtonLogChooser = new javax.swing.JButton();
        jLabelMailRecepients = new javax.swing.JLabel();
        jLabelErrorHandling = new javax.swing.JLabel();
        jTextMailRecipients = new javax.swing.JTextField();
        jLabelMailHost = new javax.swing.JLabel();
        jTextMailHost = new javax.swing.JTextField();
        jLabelMailSender = new javax.swing.JLabel();
        jTextMailSender = new javax.swing.JTextField();
        jLabelMailUser = new javax.swing.JLabel();
        jTextMailUser = new javax.swing.JTextField();
        jLabelMailPassword = new javax.swing.JLabel();
        jTextMailPassword = new javax.swing.JPasswordField();
        jLabelSettings = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextPaymentDBFileChooser = new javax.swing.JTextField();
        jTextPaymentDirChooser = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextPaymentCRFileChooser = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextDBVersion = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(650, 500));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(at.jollydays.booking.ui.MainUI.class).getContext().getResourceMap(JPanelSettings.class);
        jTextARLastNumber.setText(resourceMap.getString("jTextARLastNumber.text")); // NOI18N
        jTextARLastNumber.setName("jTextARLastNumber"); // NOI18N

        jLabelARNextNumber.setText(resourceMap.getString("jLabelARNextNumber.text")); // NOI18N
        jLabelARNextNumber.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelARNextNumber.setName("jLabelARNextNumber"); // NOI18N

        jTextARPacketSize.setText(resourceMap.getString("jTextARPacketSize.text")); // NOI18N
        jTextARPacketSize.setName("jTextARPacketSize"); // NOI18N

        jLabelARPacketSize.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelARPacketSize.setText(resourceMap.getString("jLabelARPacketSize.text")); // NOI18N
        jLabelARPacketSize.setName("jLabelARPacketSize"); // NOI18N

        jLabelAR.setText(resourceMap.getString("jLabelAR.text")); // NOI18N
        jLabelAR.setInheritsPopupMenu(false);
        jLabelAR.setName("jLabelAR"); // NOI18N

        jLabelER.setText(resourceMap.getString("jLabelER.text")); // NOI18N
        jLabelER.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelER.setName("jLabelER"); // NOI18N

        jTextERLastNumber.setText(resourceMap.getString("jTextERLastNumber.text")); // NOI18N
        jTextERLastNumber.setName("jTextERLastNumber"); // NOI18N

        jLabelERNextNumber.setText(resourceMap.getString("jLabelERNextNumber.text")); // NOI18N
        jLabelERNextNumber.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelERNextNumber.setName("jLabelERNextNumber"); // NOI18N

        jTextERPacketSize.setText(resourceMap.getString("jTextERPacketSize.text")); // NOI18N
        jTextERPacketSize.setName("jTextERPacketSize"); // NOI18N

        jLabelERPacketSize.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelERPacketSize.setText(resourceMap.getString("jLabelERPacketSize.text")); // NOI18N
        jLabelERPacketSize.setName("jLabelERPacketSize"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(at.jollydays.booking.ui.MainUI.class).getContext().getActionMap(JPanelSettings.class, this);
        jButtonSave.setAction(actionMap.get("save")); // NOI18N
        jButtonSave.setText(resourceMap.getString("jButtonSave.text")); // NOI18N
        jButtonSave.setName("jButtonSave"); // NOI18N

        jButtonFileChooser.setAction(actionMap.get("chooseDir")); // NOI18N
        jButtonFileChooser.setText(resourceMap.getString("jButtonFileChooser.text")); // NOI18N
        jButtonFileChooser.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButtonFileChooser.setName("jButtonFileChooser"); // NOI18N

        jTextFileChooser.setText(resourceMap.getString("jTextFileChooser.text")); // NOI18N
        jTextFileChooser.setName("jTextFileChooser"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jButtonRun.setAction(actionMap.get("runAll")); // NOI18N
        jButtonRun.setText(resourceMap.getString("jButtonRun.text")); // NOI18N
        jButtonRun.setName("jButtonRun"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTextLogChooser.setText(resourceMap.getString("jTextLogChooser.text")); // NOI18N
        jTextLogChooser.setName("jTextLogChooser"); // NOI18N

        jButtonLogChooser.setAction(actionMap.get("chooseLog")); // NOI18N
        jButtonLogChooser.setText(resourceMap.getString("jButtonLogChooser.text")); // NOI18N
        jButtonLogChooser.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButtonLogChooser.setName("jButtonLogChooser"); // NOI18N

        jLabelMailRecepients.setText(resourceMap.getString("jLabelMailRecepients.text")); // NOI18N
        jLabelMailRecepients.setName("jLabelMailRecepients"); // NOI18N

        jLabelErrorHandling.setFont(resourceMap.getFont("jLabelErrorHandling.font")); // NOI18N
        jLabelErrorHandling.setText(resourceMap.getString("jLabelErrorHandling.text")); // NOI18N
        jLabelErrorHandling.setName("jLabelErrorHandling"); // NOI18N

        jTextMailRecipients.setText(resourceMap.getString("jTextMailRecipients.text")); // NOI18N
        jTextMailRecipients.setName("jTextMailRecipients"); // NOI18N

        jLabelMailHost.setText(resourceMap.getString("jLabelMailHost.text")); // NOI18N
        jLabelMailHost.setName("jLabelMailHost"); // NOI18N

        jTextMailHost.setText(resourceMap.getString("jTextMailHost.text")); // NOI18N
        jTextMailHost.setName("jTextMailHost"); // NOI18N

        jLabelMailSender.setText(resourceMap.getString("jLabelMailSender.text")); // NOI18N
        jLabelMailSender.setName("jLabelMailSender"); // NOI18N

        jTextMailSender.setText(resourceMap.getString("jTextMailSender.text")); // NOI18N
        jTextMailSender.setName("jTextMailSender"); // NOI18N

        jLabelMailUser.setText(resourceMap.getString("jLabelMailUser.text")); // NOI18N
        jLabelMailUser.setName("jLabelMailUser"); // NOI18N

        jTextMailUser.setText(resourceMap.getString("jTextMailUser.text")); // NOI18N
        jTextMailUser.setName("jTextMailUser"); // NOI18N

        jLabelMailPassword.setText(resourceMap.getString("jLabelMailPassword.text")); // NOI18N
        jLabelMailPassword.setName("jLabelMailPassword"); // NOI18N

        jTextMailPassword.setText(resourceMap.getString("jTextMailPassword.text")); // NOI18N
        jTextMailPassword.setName("jTextMailPassword"); // NOI18N

        jLabelSettings.setFont(resourceMap.getFont("jLabelSettings.font")); // NOI18N
        jLabelSettings.setText(resourceMap.getString("jLabelSettings.text")); // NOI18N
        jLabelSettings.setName("jLabelSettings"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jTextPaymentDBFileChooser.setText(resourceMap.getString("jTextPaymentDBFileChooser.text")); // NOI18N
        jTextPaymentDBFileChooser.setName("jTextPaymentDBFileChooser"); // NOI18N

        jTextPaymentDirChooser.setText(resourceMap.getString("jTextPaymentDirChooser.text")); // NOI18N
        jTextPaymentDirChooser.setName("jTextPaymentDirChooser"); // NOI18N

        jButton1.setAction(actionMap.get("choosePaymentDBFile")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setAction(actionMap.get("choosePaymentDir")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jTextPaymentCRFileChooser.setText(resourceMap.getString("jTextPaymentCRFileChooser.text")); // NOI18N
        jTextPaymentCRFileChooser.setName("jTextPaymentCRFileChooser"); // NOI18N

        jButton3.setAction(actionMap.get("choosePaymentCRFile")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jTextDBVersion.setText(resourceMap.getString("jTextDBVersion.text")); // NOI18N
        jTextDBVersion.setName("jTextDBVersion"); // NOI18N

        jButton4.setAction(actionMap.get("wiki")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N

        jButton5.setAction(actionMap.get("runAR")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N

        jButton6.setAction(actionMap.get("runER")); // NOI18N
        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N

        jButton7.setAction(actionMap.get("runKZ")); // NOI18N
        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N

        jButton8.setAction(actionMap.get("runStorno")); // NOI18N
        jButton8.setText(resourceMap.getString("jButton8.text")); // NOI18N
        jButton8.setName("jButton8"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                                        .addComponent(jLabelMailHost, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                                        .addComponent(jLabelMailSender, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                                        .addComponent(jLabelMailUser, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                                        .addComponent(jLabelMailPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                                        .addComponent(jLabelER, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                                        .addComponent(jLabelAR, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonRun, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(142, 142, 142))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelMailRecepients, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSave, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelARPacketSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelERPacketSize, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextARPacketSize)
                                    .addComponent(jTextERPacketSize, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelARNextNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelERNextNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextERLastNumber)
                                    .addComponent(jTextARLastNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextLogChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(jTextFileChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(jTextPaymentDBFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(jTextPaymentCRFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonLogChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonFileChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jTextMailHost, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(jTextMailSender, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(jTextMailUser, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(jTextMailPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(jTextMailRecipients, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextDBVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextPaymentDirChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelErrorHandling, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                        .addGap(535, 535, 535))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(890, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAR)
                    .addComponent(jLabelARPacketSize)
                    .addComponent(jTextARPacketSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelARNextNumber)
                    .addComponent(jTextARLastNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelER)
                        .addComponent(jLabelERPacketSize))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextERPacketSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelERNextNumber)
                        .addComponent(jTextERLastNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextLogChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLogChooser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextPaymentDBFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextPaymentCRFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextPaymentDirChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jTextDBVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErrorHandling)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMailRecepients)
                            .addComponent(jTextMailRecipients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextMailHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMailHost)))
                    .addComponent(jButtonFileChooser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextMailSender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMailSender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextMailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMailUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextMailPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMailPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonRun)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void save() {
        int nextARNumber = 0;
        int sizeARPacket = 100;
        int nextERNumber = 0;
        int sizeERPacket = 100;
        String choosenDir = Globals.EMPTYSTRING;
        String choosenLog = Globals.EMPTYSTRING;
        String choosenPaymentDBFile = Globals.EMPTYSTRING;
        String choosenPaymentCRFile = Globals.EMPTYSTRING;
        String choosenPaymentDir = Globals.EMPTYSTRING;

        String mailReceivers = Globals.EMPTYSTRING;
        String mailSender = Globals.EMPTYSTRING;
        String mailHost = Globals.EMPTYSTRING;
        String mailUser = Globals.EMPTYSTRING;
        String mailPassword = Globals.EMPTYSTRING;

        String dbVersion = Globals.EMPTYSTRING;

        try {
            nextARNumber = Integer.parseInt(jTextARLastNumber.getText());
        } catch (Exception ex) {
        }
        try {
            sizeARPacket = Integer.parseInt(jTextARPacketSize.getText());
        } catch (Exception ex) {
        }
        try {
            nextERNumber = Integer.parseInt(jTextERLastNumber.getText());
        } catch (Exception ex) {
        }
        try {
            sizeERPacket = Integer.parseInt(jTextERPacketSize.getText());
        } catch (Exception ex) {
        }

        try {
            choosenDir = jTextFileChooser.getText();
        } catch (Exception ex) {
        }

        try {
            choosenLog = jTextLogChooser.getText();
        } catch (Exception ex) {
        }

        try {
            choosenPaymentDBFile = jTextPaymentDBFileChooser.getText();
        } catch (Exception ex) {
        }

        try {
            choosenPaymentCRFile = jTextPaymentCRFileChooser.getText();
        } catch (Exception ex) {
        }
        
        try {
            choosenPaymentDir = jTextPaymentDirChooser.getText();
        } catch (Exception ex) {
        }

        try {
            mailReceivers = jTextMailRecipients.getText();
        } catch (Exception ex) {
        }

        try {
            mailSender = jTextMailSender.getText();
        } catch (Exception ex) {
        }

        try {
            mailHost = jTextMailHost.getText();
        } catch (Exception ex) {
        }
        try {
            mailUser = jTextMailUser.getText();
        } catch (Exception ex) {
        }
        try {
            mailPassword = String.valueOf(jTextMailPassword.getPassword());
        } catch (Exception ex) {
        }

        try {
            dbVersion = String.valueOf(jTextDBVersion.getText());
        } catch (Exception ex) {
        }


        configurationController.setProperty(Globals.ARLASTNUMBER, Integer.toString(nextARNumber));
        configurationController.setProperty(Globals.ARPACKETSIZE, Integer.toString(sizeARPacket));
        configurationController.setProperty(Globals.ERLASTNUMBER, Integer.toString(nextERNumber));
        configurationController.setProperty(Globals.ERPACKETSIZE, Integer.toString(sizeERPacket));
        configurationController.setProperty(Globals.DIRCSVFILES, choosenDir);
        configurationController.setProperty(Globals.DIRLOGFILES, choosenLog);
        configurationController.setProperty(Globals.FILEDBPAYMENT, choosenPaymentDBFile);
        configurationController.setProperty(Globals.FILECRPAYMENT, choosenPaymentCRFile);
        configurationController.setProperty(Globals.DIRPAYMENTDIR, choosenPaymentDir);
        configurationController.setProperty(Globals.MAILRECIPIENT, mailReceivers);
        configurationController.setProperty(Globals.MAILSENDER, mailSender);
        configurationController.setProperty(Globals.MAILHOST, mailHost);
        configurationController.setProperty(Globals.MAILUSER, mailUser);
        configurationController.setProperty(Globals.MAILPASSWORD, mailPassword);
        configurationController.setProperty(Globals.DBVERSION, dbVersion);

    }

    @Action
    public void chooseDir() {

        final JFileChooser fc = new JFileChooser(jTextFileChooser.getText());
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        fc.showOpenDialog(this);
        try {
            // Open an input stream
            //Scanner reader = new Scanner(fc.getSelectedFile());
            jTextFileChooser.setText(fc.getSelectedFile().getCanonicalPath());
        } catch (Exception ex) {
        }

    }

    @Action
    public void chooseLog() {

        final JFileChooser fc = new JFileChooser(jTextLogChooser.getText());
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        fc.showOpenDialog(this);
        try {
            // Open an input stream
            //Scanner reader = new Scanner(fc.getSelectedFile());
            jTextLogChooser.setText(fc.getSelectedFile().getCanonicalPath());
        } catch (Exception ex) {
        }

    }

    @Action
    public void runAll() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Processing.processing();
        setValues();

        int lastNumberAR = Integer.parseInt(configurationController.getProperty(Globals.ARLASTNUMBER).getValue());
        int lastNumberER= Integer.parseInt(configurationController.getProperty(Globals.ERLASTNUMBER).getValue());
        jTextARLastNumber.setText(Integer.toString(lastNumberAR));
        jTextERLastNumber.setText(Integer.toString(lastNumberER));

        this.setCursor(Cursor.getDefaultCursor());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonFileChooser;
    private javax.swing.JButton jButtonLogChooser;
    private javax.swing.JButton jButtonRun;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAR;
    private javax.swing.JLabel jLabelARNextNumber;
    private javax.swing.JLabel jLabelARPacketSize;
    private javax.swing.JLabel jLabelER;
    private javax.swing.JLabel jLabelERNextNumber;
    private javax.swing.JLabel jLabelERPacketSize;
    private javax.swing.JLabel jLabelErrorHandling;
    private javax.swing.JLabel jLabelMailHost;
    private javax.swing.JLabel jLabelMailPassword;
    private javax.swing.JLabel jLabelMailRecepients;
    private javax.swing.JLabel jLabelMailSender;
    private javax.swing.JLabel jLabelMailUser;
    private javax.swing.JLabel jLabelSettings;
    private javax.swing.JTextField jTextARLastNumber;
    private javax.swing.JTextField jTextARPacketSize;
    private javax.swing.JTextField jTextDBVersion;
    private javax.swing.JTextField jTextERLastNumber;
    private javax.swing.JTextField jTextERPacketSize;
    private javax.swing.JTextField jTextFileChooser;
    private javax.swing.JTextField jTextLogChooser;
    private javax.swing.JTextField jTextMailHost;
    private javax.swing.JPasswordField jTextMailPassword;
    private javax.swing.JTextField jTextMailRecipients;
    private javax.swing.JTextField jTextMailSender;
    private javax.swing.JTextField jTextMailUser;
    private javax.swing.JTextField jTextPaymentCRFileChooser;
    private javax.swing.JTextField jTextPaymentDBFileChooser;
    private javax.swing.JTextField jTextPaymentDirChooser;
    // End of variables declaration//GEN-END:variables

    private void setValues() {
        configurationController = ((MainUI) Application.getInstance()).getConfigurationController();

        try {
            jTextARLastNumber.setText(configurationController.getProperty(Globals.ARLASTNUMBER).getValue());
        } catch (Exception ex) {
        }

        try {
            jTextARPacketSize.setText(configurationController.getProperty(Globals.ARPACKETSIZE).getValue());
        } catch (Exception ex) {
        }

        try {
            jTextERLastNumber.setText(configurationController.getProperty(Globals.ERLASTNUMBER).getValue());
        } catch (Exception ex) {
        }

        try {
            jTextERPacketSize.setText(configurationController.getProperty(Globals.ERPACKETSIZE).getValue());
        } catch (Exception ex) {
        }

        try {
            jTextFileChooser.setText(configurationController.getProperty(Globals.DIRCSVFILES).getValue());
        } catch (Exception ex) {
        }

        try {
            jTextLogChooser.setText(configurationController.getProperty(Globals.DIRLOGFILES).getValue());
        } catch (Exception ex) {
        }

        try {
            jTextPaymentDBFileChooser.setText(configurationController.getProperty(Globals.FILEDBPAYMENT).getValue());
        } catch (Exception ex) {
        }

        try {
            jTextPaymentCRFileChooser.setText(configurationController.getProperty(Globals.FILECRPAYMENT).getValue());
        } catch (Exception ex) {
        }

        try {
            jTextPaymentDirChooser.setText(configurationController.getProperty(Globals.DIRPAYMENTDIR).getValue());
        } catch (Exception ex) {
        }

        try {
            jTextMailRecipients.setText(configurationController.getProperty(Globals.MAILRECIPIENT).getValue());
        } catch (Exception ex) {
        }
        try {
            jTextMailSender.setText(configurationController.getProperty(Globals.MAILSENDER).getValue());
        } catch (Exception ex) {
        }
        try {
            jTextMailHost.setText(configurationController.getProperty(Globals.MAILHOST).getValue());
        } catch (Exception ex) {
        }
        try {
            jTextMailUser.setText(configurationController.getProperty(Globals.MAILUSER).getValue());
        } catch (Exception ex) {
        }
        try {
            jTextMailPassword.setText(configurationController.getProperty(Globals.MAILPASSWORD).getValue());
        } catch (Exception ex) {
        }
        try {
            jTextDBVersion.setText(configurationController.getProperty(Globals.DBVERSION).getValue());
        } catch (Exception ex) {
        }

    }

    @Action
    public void choosePaymentDBFile() {

        final JFileChooser fc = new JFileChooser(jTextPaymentDBFileChooser.getText());
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        fc.showOpenDialog(this);
        try {
            // Open an input stream
            //Scanner reader = new Scanner(fc.getSelectedFile());
            jTextPaymentDBFileChooser.setText(fc.getSelectedFile().getCanonicalPath());
        } catch (Exception ex) {
        }

    }

    @Action
    public void choosePaymentDir() {

        final JFileChooser fc = new JFileChooser(jTextPaymentDirChooser.getText());
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        fc.showOpenDialog(this);
        try {
            // Open an input stream
            //Scanner reader = new Scanner(fc.getSelectedFile());
            jTextPaymentDirChooser.setText(fc.getSelectedFile().getCanonicalPath());
        } catch (Exception ex) {
        }

    }

    @Action
    public void choosePaymentCRFile() {

        final JFileChooser fc = new JFileChooser(jTextPaymentCRFileChooser.getText());
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        fc.showOpenDialog(this);
        try {
            // Open an input stream
            //Scanner reader = new Scanner(fc.getSelectedFile());
            jTextPaymentCRFileChooser.setText(fc.getSelectedFile().getCanonicalPath());
        } catch (Exception ex) {
        }

    }

    @Action
    public void wiki() {
        try {
            Desktop desktop = Desktop.getDesktop();
            desktop.browse(new URI(Globals.WIKIURL));
        } catch (Exception ex) {
        }
    }

    @Action
    public void runAR() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Processing.processingSpecific(true, false, false, false);
        setValues();
        int lastNumberAR = Integer.parseInt(configurationController.getProperty(Globals.ARLASTNUMBER).getValue());
        jTextARLastNumber.setText(Integer.toString(lastNumberAR));
        this.setCursor(Cursor.getDefaultCursor());
    }

    @Action
    public void runER() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Processing.processingSpecific(false, true, false, false);
        setValues();
        int lastNumberER= Integer.parseInt(configurationController.getProperty(Globals.ERLASTNUMBER).getValue());
        jTextERLastNumber.setText(Integer.toString(lastNumberER));
        this.setCursor(Cursor.getDefaultCursor());
    }

    @Action
    public void runKZ() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Processing.processingSpecific(false, false, true, false);
        setValues();
        this.setCursor(Cursor.getDefaultCursor());
    }

    @Action
    public void runStorno() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        Processing.processingSpecific(false, false, false, true);
        setValues();
        this.setCursor(Cursor.getDefaultCursor());    }
}
